export const PRIMARY_COLOR = '#f23d06'
export const COLOR_PRIMARY_VARIANT = '#4cd88b'
export const COLOR_ON_PRIMARY = '#bfbfbf'
export const ERROR = '#FF0000'
export const GRAY = '#808080'
export const LIGHT_GRAY = '#d3d3d3'